-- LOI_V_WH_INVENTORY_ALL_FCST 物化视图定义
-- 来源: Oracle LOGPOE 用户, 2026-05-27
-- 注意: 此定义通过用户逐段粘贴收集，可能不完整

CREATE MATERIALIZED VIEW "LOGPOE"."LOI_V_WH_INVENTORY_ALL_FCST" (
    "PLANT", "MATERIAL", "CALNDR_DATE", "MATERIAL_TYPE", "MRP_TYPE", 
    "CUSTOMER_NAME", "VALUATION_CLASS", "MRP_CONTROLLER", "PROCUREMENT_TYPE", 
    "SPECIAL_PROCUREMENT_TYPE", "PROFIT_CENTER", "MATERIAL_PRICE", "STOCK_QTY", "VALUE"
)
SEGMENT CREATION IMMEDIATE
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "RBCDLOG" NO INMEMORY
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE

-- 业务逻辑: 结合采购计划、生产订单、当前库存，预测未来库存
-- 数据血缘: FCT_PURCHASE_SCHEDULE + PLAUF_POE_H + INVENTORY_ALL + RESB_POE + VBBE_DEMAND_REPORT + RB04_YA3_VPBED_PA5 + DIM_MATERIAL

AS 
WITH SCHEDULE_PURCHASE AS (
    -- 采购计划：运输时间计算 + 开放数量
    SELECT A.PLANT, A.MATERIAL_NUMBER AS MATERIAL,
        TO_DATE(A.SCHEDULE_LINE_DELIVERY_DATE,'YYYYMMDD') AS SCHEDULE_DATE,
        CASE 
            WHEN A.TRANSPORTATION_PLANNING_DATE = '00000000' THEN TO_DATE(A.DELIVERY_DATE,'YYYYMMDD')
            ELSE TO_DATE(A.TRANSPORTATION_PLANNING_DATE,'YYYYMMDD')
        END TT_DATE,
        0 AS TT, A.QTY AS SCHEDULED_QTY, 0 AS DELIVERED_QTY, A.QTY AS REDUCED_QTY, A.QTY AS OPEN_QTY, B.MRP_TYPE
    FROM LOI_V_BASE_INBOUND A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B
    ON A.PLANT = B.PLANT AND A.MATERIAL = B.MATERIAL
    WHERE A.GOODS_MOVEMENT_STATUS in ('A','B') AND A.QTY>0
    ORDER BY SCHEDULE_DATE
),

INV AS (
    -- 当前库存
    SELECT PLANT, TRUNC(SYSDATE) AS CALNDR_DATE, MATERIAL, NVL(OPEN_QTY,0) AS STOCK_QTY, 0 AS GIT_QTY, 'BACKLOG' AS RECORD_TYPE
    FROM SCHEDULE_PURCHASE
    WHERE SCHEDULE_DATE <= TRUNC(SYSDATE)
    
    UNION ALL
    
    -- 采购订单未来需求
    SELECT PLANT, SCHEDULE_DATE AS CALNDR_DATE, MATERIAL, NVL(OPEN_QTY,0) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_PURCHASE' AS RECORD_TYPE
    FROM SCHEDULE_PURCHASE
    WHERE SCHEDULE_DATE > TRUNC(SYSDATE)
    
    UNION ALL
    
    -- 生产订单 backlog
    SELECT PLWRK AS PLANT, TRUNC(SYSDATE) AS CALNDR_DATE, MATNR AS MATERIAL, NVL(GSMNG,0) AS STOCK_QTY, 0 AS GIT_QTY, 'BACKLOG' AS RECORD_TYPE
    FROM PLAUF_POE_H
    WHERE TO_DATE(PEDTR,'YYYYMMDD') <= TRUNC(SYSDATE)
    AND PAART in ('PE','LA')
    AND MATNR in (SELECT DISTINCT material from LOGPOE.VBBE_DEMAND_REPORT)
    
    UNION ALL
    
    -- 生产订单未来需求
    SELECT PLWRK AS PLANT, TO_DATE(PEDTR,'YYYYMMDD') AS CALNDR_DATE, MATNR AS MATERIAL, NVL(GSMNG,0) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_PRODUCTION' AS RECORD_TYPE
    FROM PLAUF_POE_H
    WHERE TO_DATE(PEDTR,'YYYYMMDD') > TRUNC(SYSDATE)
    AND PAART in ('PE','LA')
    AND MATNR in (SELECT DISTINCT material from LOGPOE.VBBE_DEMAND_REPORT)
    
    UNION ALL
    
    -- 当前库存
    SELECT PLANT, LOG_DATE AS CALNDR_DATE, MATERIAL, SUM(NVL(INVENTORY_QTY,0)) AS STOCK_QTY, 0 AS GIT_QTY, 'CURRENT' AS RECORD_TYPE
    FROM LOGPOE.INVENTORY_ALL
    WHERE IS_LATEST='Y' AND RECORD_TYPE IN ('STOCK_ON_HAND', 'SUBCONTRACT')
    GROUP BY PLANT, LOG_DATE, MATERIAL
    
    UNION ALL
    
    -- 10位需求上层需求的 backlog (消耗)
    SELECT A.WERKS AS PLANT, TRUNC(SYSDATE) AS CALNDR_DATE, A.MATNR AS MATERIAL, NVL(A.BDMNG,0)*(-1) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_CONSUMPTION' AS RECORD_TYPE
    FROM LOGPOE.RESB_POE A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.WERKS = B.PLANT AND A.MATNR = B.MATERIAL
    WHERE TO_DATE(A.BDTER,'yyyymmdd') <= TRUNC(SYSDATE) AND B.MRP_TYPE <>'YI'
    
    UNION ALL
    
    -- AWT backlog
    SELECT A.PLANT, TRUNC(SYSDATE) AS CALNDR_DATE, A.MATERIAL, NVL(A.SCHEDULED_QTY,0)*(-1) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_CONSUMPTION' AS RECORD_TYPE
    FROM LOGPOE.VBBE_DEMAND_REPORT A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.PLANT = B.PLANT AND A.MATERIAL = B.MATERIAL
    WHERE A.LOADING_DATE <= TRUNC(SYSDATE) AND (B.MRP_TYPE <>'YI' or B.MRP_TYPE IS NULL)
    
    UNION ALL
    
    -- FCST backlog (贸易件)
    SELECT A.WERKS AS PLANT, TO_DATE(A.SPTAG, 'YYYYMMDD') AS CALNDR_DATE, A.MATNR AS MATERIAL, A.MNG02 * (-1) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_CONSUMPTION' AS RECORD_TYPE
    FROM LOGPOE.RB04_YA3_VPBED_PA5 A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.WERKS = B.PLANT AND A.MATNR = B.MATERIAL
    WHERE TO_DATE(A.SPTAG, 'YYYYMMDD') <= sysdate AND (B.MRP_TYPE <> 'YI' OR B.MRP_TYPE IS NULL)
    
    UNION ALL
    
    -- 10位上层未来需求
    SELECT A.WERKS AS PLANT, TO_DATE(A.BDTER,'yyyymmdd') AS CALNDR_DATE, A.MATNR AS MATERIAL, NVL(A.BDMNG,0)*(-1) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_CONSUMPTION' AS RECORD_TYPE
    FROM LOGPOE.RESB_POE A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.WERKS = B.PLANT AND A.MATNR = B.MATERIAL
    WHERE TO_DATE(A.BDTER,'yyyymmdd') > TRUNC(SYSDATE) AND B.MRP_TYPE <>'YI'
    
    UNION ALL
    
    -- AWT future demand
    SELECT A.PLANT, A.LOADING_DATE AS CALNDR_DATE, A.MATERIAL, NVL(A.SCHEDULED_QTY,0)*(-1) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_CONSUMPTION' AS RECORD_TYPE
    FROM LOGPOE.VBBE_DEMAND_REPORT A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.PLANT = B.PLANT AND A.MATERIAL = B.MATERIAL
    WHERE A.LOADING_DATE > TRUNC(SYSDATE) AND (B.MRP_TYPE <>'YI' or B.MRP_TYPE IS NULL)
    
    UNION ALL
    
    -- FCST future (贸易件)
    SELECT A.WERKS AS PLANT, TO_DATE(A.SPTAG, 'YYYYMMDD') AS CALNDR_DATE, A.MATNR AS MATERIAL, A.MNG02 * (-1) AS STOCK_QTY, 0 AS GIT_QTY, 'FORECAST_CONSUMPTION' AS RECORD_TYPE
    FROM LOGPOE.RB04_YA3_VPBED_PA5 A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.WERKS = B.PLANT AND A.MATNR = B.MATERIAL
    WHERE TO_DATE(A.SPTAG, 'YYYYMMDD') > sysdate AND (B.MRP_TYPE <> 'YI' OR B.MRP_TYPE IS NULL)
    ORDER BY CALNDR_DATE
),

PN AS (
    -- 物料+日期维度（未来90天）
    SELECT PLANT, CALNDR_DATE, MATERIAL
    FROM (SELECT PLANT, MATERIAL, VALUATION_CLASS, PROCUREMENT_TYPE FROM LOGPOE.DIM_MATERIAL where MRP_CONTROLLER !='W34'), DIM_DATE
    WHERE CALNDR_DATE BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE)+90
),

LATEST_INV AS (
    SELECT A.PLANT, A.MATERIAL, A.LOG_DATE AS CALNDR_DATE, B.MATERIAL_TYPE, B.MRP_TYPE, B.VALUATION_CLASS, B.MRP_CONTROLLER,
        B.PROCUREMENT_TYPE, B.SPECIAL_PROCUREMENT_TYPE, B.PROFIT_CENTER, B.material_price, NVL(SUM(A.INVENTORY_QTY),0) AS STOCK_QTY
    FROM LOGPOE.INVENTORY_ALL A
    LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.PLANT || A.MATERIAL = B.PLANT || B.MATERIAL
    WHERE A.IS_LATEST='Y' AND A.RECORD_TYPE IN ('STOCK_ON_HAND', 'SUBCONTRACT')
    GROUP BY A.PLANT, A.MATERIAL, A.LOG_DATE, B.MATERIAL_TYPE, B.MRP_TYPE, B.VALUATION_CLASS, B.MRP_CONTROLLER, B.PROCUREMENT_TYPE, B.SPECIAL_PROCUREMENT_TYPE, B.PROFIT_CENTER, B.material_price
),

SUMMARY AS (
    SELECT PLANT, MATERIAL, CALNDR_DATE, MATERIAL_TYPE, MRP_TYPE, VALUATION_CLASS, MRP_CONTROLLER, PROCUREMENT_TYPE, SPECIAL_PROCUREMENT_TYPE, PROFIT_CENTER, material_price,
        SUM(STOCK_QTY) OVER (PARTITION BY PLANT, MATERIAL ORDER BY CALNDR_DATE) AS STOCK_QTY
    FROM (
        SELECT A.PLANT, A.MATERIAL, A.CALNDR_DATE, SUM(A.STOCK_QTY) AS STOCK_QTY, B.MATERIAL_TYPE, B.MRP_TYPE, B.VALUATION_CLASS, B.MRP_CONTROLLER, B.PROCUREMENT_TYPE, B.SPECIAL_PROCUREMENT_TYPE, B.PROFIT_CENTER, B.material_price
        FROM (
            SELECT A.PLANT, A.CALNDR_DATE, A.MATERIAL, NVL(B.STOCK_QTY,0) AS STOCK_QTY
            FROM PN A
            LEFT OUTER JOIN INV B ON A.CALNDR_DATE=B.CALNDR_DATE AND A.MATERIAL=B.MATERIAL AND A.PLANT=B.PLANT
        ) A
        LEFT OUTER JOIN LOI_V_BASE_MATERIAL_MASTER B ON A.PLANT || A.MATERIAL = B.PLANT || B.MATERIAL
        GROUP BY A.PLANT, A.MATERIAL, A.CALNDR_DATE, B.MATERIAL_TYPE, B.MRP_TYPE, B.VALUATION_CLASS, B.MRP_CONTROLLER, B.PROCUREMENT_TYPE, B.SPECIAL_PROCUREMENT_TYPE, B.PROFIT_CENTER, B.material_price
    )
    ORDER BY PLANT ASC, CALNDR_DATE ASC, MATERIAL ASC
)

-- 最终输出（此处为用户粘贴的后续部分，可能不完整）
-- 后续包含 VALUE 计算、GIT_QTY 等逻辑
